### ISSUE TITLE
Use Application Default Credentials (ADC) standard

### ISSUE THREAD

**Issue by aredev** [stackkit/laravel-google-cloud-tasks-queue#1]
When deploying this package to Google Cloud it complains that there is no credentials file included. I created a simple fork 'bypassing' this issue by adhering to Application Default Credentials standard.

- For local development where you need to have a service account json file, you set the `GOOGLE_APPLICATION_CREDENTIALS` in your `.env` file.
- For deployment to Google Cloud (not limited to App Engine), you omit this environment variable as Google Cloud will return to the default service account that Compute Engine, Google Kubernetes Engine, App Engine, Cloud Run, and Cloud Functions provide.

More information can be found [here](https://cloud.google.com/docs/authentication/production) 

In my fork I removed the validation on the credentials file and also removed the `credentials`  option in the constructor of the `CloudTasksClient` class. However, there might be better solutions.

**Comment by marickvantuil** [comment]
Thanks! I wasn't aware of that. I have made a new release (2.0.0) with these changes.
