### ISSUE TITLE
ApiCore exception

### ISSUE THREAD

**Issue by shyfter-co** [stackkit/laravel-google-cloud-tasks-queue#10]
Hi,

I have such an error when calling : "EchoOutput::dispatch(new \DateTime());"

"file": "/vendor/google/gax/src/ApiException.php",
            "line": 109,
            "function": "create",
            "class": "Google\\ApiCore\\ApiException",
            "type": "::",
            "args": [
                "Request contains an invalid argument.",
                3,
                null,
                [],
                null
            ]

**Comment by marickvantuil** [comment]
Hi, can you provide me with some more info as to what you are doing exactly? Some reproducible steps or preferably a test repository would really help here.
From what I can see of your error, some argument sent to Google Cloud REST API is invalid (RPC code 3).
