### ISSUE TITLE
Google\ApiCore\ApiException: { "message": "Queue does not exist.", "code": 9, "status": "FAILED_PRECONDITION", "details": [] }

### ISSUE THREAD

**Issue by i386** [stackkit/laravel-google-cloud-tasks-queue#103]
Sometimes the task names are not formatted in the correct googley way and you get errors like the following... would be helpful if Google's SDK wasn't a huge ball of async garbage that doesn't produce sane stack traces OR if google just told you what the invalid input is (trust me I have been onto the product peoples case about that.

```
PHP Notice: Google\ApiCore\ApiException: { "message": "Queue does not exist.", "code": 9, "status": "FAILED_PRECONDITION", "details": [] }
```

<img width="1637" alt="image" src="https://github.com/stackkit/laravel-google-cloud-tasks-queue/assets/50156/b6d0f64e-873b-43b8-9062-e778d342152c">

**Comment by marickvantuil** [comment]
Is there more info like the task name that isn't formatted correctly? Kind of strange that it's so random?!

**Comment by i386** [comment]
@marickvantuil nope, the API doesn't tell you what name is invalid... very weird.

**Comment by tiagoamaka** [comment]
@i386 the queue is not created automatically on the cloud task (which could be an improvement), so you need to create it manually.
