### ISSUE TITLE
Issue authenticating Access Token

### ISSUE THREAD

**Issue by TheFetchZen** [stackkit/laravel-google-cloud-tasks-queue#111]
Hello,

I started getting this error today:

`ErrorException: openssl_verify(): supplied key param cannot be coerced into a public key in /var/www/html/vendor/firebase/php-jwt/src/JWT.php:301
`
It seems that the Google/Auth library might be causing the issue.

See the below stacktrace
`#1 /var/www/html/vendor/firebase/php-jwt/src/JWT.php(301): openssl_verify('JSUzI...', '\xAF2\xEF\xB0\xF6[\xE1\xBD\xE3\xCE\xA5\f\xC0\xE8\x05...', '-----BEGIN RSA ...', 'SHA256')
#2 /var/www/html/vendor/firebase/php-jwt/src/JWT.php(144): Firebase\JWT\JWT::verify('JSUzI...', '\xAF2\xEF\xB0\xF6[\xE1\xBD\xE3\xCE\xA5\f\xC0\xE8\x05...', '-----BEGIN RSA ...', 'RS256')
#3 [internal function]: Firebase\JWT\JWT::decode('eyJhbGciOiJSUzI...', Array)
#4 /var/www/html/vendor/google/auth/src/AccessToken.php(474): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/google/auth/src/AccessToken.php(249): Google\Auth\AccessToken->callJwtStatic('decode', Array)`

**Comment by marickvantuil** [comment]
Been getting this error too - reverted phpseclib back to 2.x, can you update this package and check if that fixes it?

**Comment by TheFetchZen** [comment]
Thanks, the reverted version worked again

**Comment by fabricekadonation** [comment]
@marickvantuil we need phpseclib for other parts of our application, is it possible to make the code compatible for phpseclib 3.x?

**Comment by marickvantuil** [comment]
@fabricekadonation I really want to update it, but I'm still getting the errors in [this GitHub issue](https://github.com/googleapis/google-auth-library-php/issues/457) when updating phpseclib to 3.x. The error happens in `google-auth-library-php` and I sadly don't have enough knowledge of what's going wrong!

**Comment by marickvantuil** [comment]
@fabricekadonation Actually I had a look around and might have fixed the issue in the Google library, made a [PR](https://github.com/googleapis/google-auth-library-php/pull/466). Let's hope it gets merged soon. 👍

**Comment by fabricekadonation** [comment]
@marickvantuil thanks for opening the PR. Very weird but locally it now seems to work without any changes. I will test on our production server to see if it works there as well.
