### ISSUE TITLE
Database never logs latest error

### ISSUE THREAD

**Issue by tiagoamaka** [stackkit/laravel-google-cloud-tasks-queue#118]
Hi there, firstly thank you very much for the fantastic package.

I have found a bug regarding the retries. I have setup my cloud task to retry only twice (2 retries), and then I forced a bug on my job to get those retries and see what happens, but every time on the second (last) retry, the job is gone on the google cloud task but on the database it's stuck on `running` and it never logs the latest error log:

<img width="952" alt="image" src="https://github.com/stackkit/laravel-google-cloud-tasks-queue/assets/134358954/a47837d9-e86a-4a94-8d49-69155d0ff9dc">

```
{
    "events": [
        {
            "queue": "quickbooks-staging",
            "status": "queued",
            "datetime": "2023-09-05 00:42:26"
        },
        {
            "status": "running",
            "datetime": "2023-09-05 00:42:40"
        },
        {
            "status": "error",
            "datetime": "2023-09-05 00:42:43"
        },
        {
            "status": "running",
            "datetime": "2023-09-05 00:42:57"
        }
    ],
    "payload": "...",
    "exception": "..."
}
```

I'm using the latest version of the package, v3.6.0.

Thank you, appreciate your help.

**Comment by marickvantuil** [comment]
Thanks, will look into it soon!

**Comment by marickvantuil** [comment]
Hi, I'm closing this issue as I wasn't able to reproduce it. If you have more info I'd be happy to look into it again.
