### ISSUE TITLE
Subpath in STACKKIT_CLOUD_TASKS_HANDLER throws Exception

### ISSUE THREAD

**Issue by marcoMontoXnoova** [stackkit/laravel-google-cloud-tasks-queue#119]
Hi,

I have encountered an issue while using the library in my project. My Laravel application is hosted in a subpath, such as: https://example.com/laravel/here. I need to pass the domain with the subpath to the environment variable **STACKKIT_CLOUD_TASKS_HANDLER**, but it throws an exception because I have added a subpath to the URL.

While investigating the exception, I found the reason in **vendor/stackkit/laravel-google-cloud-tasks-queue/src/Config.php**
```
    // it is no longer necessary to also include the path and simply setting the handler
            // URL is enough. If someone upgrades and forgets we will warn them here.
            if (!empty($parse['path'])) {
                throw new Exception(
                    'Unable to push task to Cloud Tasks because the task handler URL (' . $handler . ') is not ' .
                    'compatible. To fix this, please remove \'' . $parse['path'] . '\' from the URL, ' .
                    'or copy from here: STACKKIT_CLOUD_TASKS_HANDLER=' . $parse['scheme'] . '://' . $parse['host']
                );
            }
```
Is it possible to handle both the deprecation of the older versions and support the feature to add a subpath?

**Comment by marickvantuil** [comment]
@marcoMontoXnoova This was fixed in `v3.6.4`. See the attached PR for more info!
