### ISSUE TITLE
Getting error in stackkit_cloud_tasks, but task is carried out correctly

### ISSUE THREAD

**Issue by larsnedb** [stackkit/laravel-google-cloud-tasks-queue#124]
Hello,
I'm having some issues with your library for my PHP Laravel application. (PHP 8.2, Laravel 9.52)

We were running version 3.3, but experienced a great amount of errors in our logs because it attempted to delete already deleted tasks. We then had someone to provide a patch for this fix, which you incorporated in version 3.4.1. See [this thread](https://github.com/stackkit/laravel-google-cloud-tasks-queue/discussions/95). But while waiting for this new official release, we have been running his fork of this project since February.

Last week I tried to change my dependency version to 3.5.0, but then I had issues with some tasks failing.
I have a queue in GCP called "mail".
It turned out that certain emails tasks queued by our application were not sent out at all, but went to `status = queued` and remained there forever in the `stackkit_cloud_tasks` table. So basically we were unable to send out Forgotten password and registration emails. But other tasks using the same queue were working without problems. It is not clear to me why some tasks were working perfectly and others not at all, especially since they are using the same queue.

As you can see from the following screenshot, it seems that the task is first created, then pushed to the queue. But the last entry in the logs, says that `attemptResponseLog.status = NOT_FOUND`.
![Skjermbilde 2023-12-01 kl  13 39 41](https://github.com/stackkit/laravel-google-cloud-tasks-queue/assets/44724910/674a4c8a-73f0-49db-aa81-0168dce6cb6e)

Today, I attempted to jump straight to version 3.6.2. This time, the task is executed and emails are actually sent from my application, but this time the tasks status in my `stackkit_cloud_tasks` table jumps straight to `error` with exception "Requested entity was not found". Full entry from `stackkit_cloud_tasks.metadata`:
```
{
  "events": [
    {
      "queue": "mail",
      "status": "queued",
      "datetime": "2023-12-04 10:26:00"
    },
    {
      "status": "running",
      "datetime": "2023-12-04 10:26:00"
    },
    {
      "status": "error",
      "datetime": "2023-12-04 10:26:01"
    }
  ],
  "payload": "<hidden>",
  "exception": "Google\\ApiCore\\ApiException: {\n    \"message\": \"Requested entity was not found.\",\n    \"code\": 5,\n    \"status\": \"NOT_FOUND\",\n    \"details\": []\n}\n"
}
```

So even though it seems that my application now is able to send out emails, I still get these errors in my logs, which I suspect also might lead to some unwanted retries.

So in version 3.5.0 some of my tasks go directly to `status = queued` and stays there forever, but in version 3.6.2, the task has `status = error`, but the tasks are actually carried out.

I'm not sure if this is enough for you to go after, but it seems there are still some issues with task statuses and maybe some unneeded deletion?
I hope you are able to have a look at this, please ask me if there is any more data I can provide for you.

**Comment by marickvantuil** [comment]
Still can't seem to crack this issue 🙃

- Can you provide the full stack/exception trace if possible?
- Where is the app running, Cloud Run/AppEngine or somewhere else?
- Is there a pattern what is or isn't working? Certain mails only? Other jobs work fine?

I'm thinking of two ways to approach it:

1. Add a fallback in case an already-deleted job is attempted to be deleted:

![Screenshot 2023-12-23 at 22 01 46](https://github.com/stackkit/laravel-google-cloud-tasks-queue/assets/647007/c8f0964b-0df0-47ea-b3bb-d51b762be0b5)

2. If the above doesn't help, release a version of the package with extensive debug logging that will hopefully uncover the issue

**Comment by larsnedb** [comment]
Hi again!
Sorry I didn't see your answer until now.
The app is running in Cloud Run. As mentioned, it fails for two specific emails, but all others seem to work out fine.

I didn't know at the time of writing the original post, but this also gave me huge issues with the database table `stackkit_cloud_tasks` which grew to more than 7GB size in relatively short time.
These problems also went away after once again downgrading to the feature branch as mentioned.

But now I am currently upgrading my project from Laravel 9 to Laravel 10, and in that regards also bumping 
`stackkit/laravel-google-cloud-tasks-queue: "^3.7"`. Now, for some reason, everything seems to work nicely :)

So I will not spend any more time debugging what gave me issues in the past, but hopefully this will continue to work now. Thank you for your time!
