### ISSUE TITLE
PAYLOAD NOT BEING POSTED to URL configured on handler

### ISSUE THREAD

**Issue by BrianOtieno12** [stackkit/laravel-google-cloud-tasks-queue#143]
Thanks for this package. Below is my function

    public function processJobs(Request $request)
    {

        Log::info(__FUNCTION__, [
            'ReceivedRequest' => $request->all(),
        ]);

        return response()->json($response = "", Response::HTTP_OK);
    }

**Comment by marickvantuil** [comment]
Hi, I'm sorry, but I will need a lot more info to even consider debugging this.
