### ISSUE TITLE
Is there any way to set the credentials JSON file using another .env var?

### ISSUE THREAD

**Issue by LeonardoRochaInacio** [stackkit/laravel-google-cloud-tasks-queue#151]
Is there any way to set the credentials JSON file using another .env var? Because on my project I'm using a separated service account for each service.

.env example:
LARAVEL_G_CLOUD_STORAGE_CREDENTIAL_PATH='.......'
LARAVEL_G_CLOUD_SCHEDULER_CREDENTIAL_PATH='.......'
LARAVEL_G_CLOUD_FIREBASE_CREDENTIAL_PATH='.......'
LARAVEL_G_CLOUD_TASKS_CREDENTIAL_PATH='.......'

**Comment by marickvantuil** [comment]
I've just released a new version that makes it possible to specify a different credentials file!

Let me know if that works!

![Screenshot 2024-08-16 at 16 45 47](https://github.com/user-attachments/assets/cb2ddd1f-e1a8-48c1-bd8d-f3a2d2215000)
