### ISSUE TITLE
INFO Maximum call stack size error due to Google

### ISSUE THREAD

**Issue by romanstingler** [stackkit/laravel-google-cloud-tasks-queue#155]
If you encounter 
```Maximum call stack size of 8339456 bytes (zend.max_allowed_stack_size - zend.reserved_stack_size) reached. Infinite recursion?```
It is due to 
https://github.com/googleapis/gax-php/issues/584

**Comment by marickvantuil** [comment]
Thanks for reporting. I've added a bit of info in the troubleshooting section of this package readme. Hopefully it'll get fixed soon.
