### ISSUE TITLE
Laravel Octane support

### ISSUE THREAD

**Issue by gabfr** [stackkit/laravel-google-cloud-tasks-queue#17]
Hello there! First of all, thanks for this package it really helps and saves me a lot of time integrating GCP Cloud Tasks in my project.

I'm using Laravel 8, along with Laravel octane, running in GCP Cloud Run. After struggling a bit with your package on this setup, I discovered that the way it tries to load the request payload in the `HandleTask` class was grabbing the wrong data and breaking the handle task action.

After doing this change: https://github.com/stackkit/laravel-google-cloud-tasks-queue/pull/16

It worked like a charm.

So, do you interest in patching your lib with this fix? If so, I can re-open the pull request.

Thanks again!

**Comment by marickvantuil** [comment]
Thanks! That sounds good, if you can re-open the pull request I will merge it.

**Comment by gabfr** [comment]
It's open again.

**Comment by marickvantuil** [comment]
Merged and released a new version `2.1.1`

Thnx!
