### ISSUE TITLE
Laravel 5.7 + PHP 7.4

### ISSUE THREAD

**Issue by riaanduplessis** [stackkit/laravel-google-cloud-tasks-queue#27]
This is simply a question regarding the compatibility list.

I was curious as to why the package cannot be used on Laravel 5.7 with PHP 7.4 since 7.4 has few breaking changes and is compatible with Laravel 5.7. 

Is there something specific that causes a compatibility issue?

Thanks in advance.

**Comment by marickvantuil** [comment]
I can't remember anymore. I think I copied the Github actions/Orchestra testbench test matrix from another package and just went with that. I think this package should work with Laravel 5.7 and PHP 7.4, as well as Laravel 5.6 and 5.5 with PHP 7.4. I'll go ahead and update it.

**Comment by marickvantuil** [comment]
Updated the compatibility list. Thanks!
