### ISSUE TITLE
Job using "X-CloudTasks-TaskExecutionCount" instead of "x-cloudtasks-taskretrycount" for attempts

### ISSUE THREAD

**Issue by mbreithu-wtd** [stackkit/laravel-google-cloud-tasks-queue#55]
In v3.x of this package, the task handler (TaskHandler.php:98) sets the header X-CloudTasks-TaskExecutionCount as the jobs attempt count. But according to the documentation, the execution count is only incremented when the task was processed, returned a response in time, and the response code is not in the 5xx code range.
In cases where the task execution returns 5xx, the retry count is incremented, but the execution count is not. 

Those cases might lead to failed tasks not being stored in the failed jobs table, because the job still has attempts < maxAttempts.

Task not being stored in the failed jobs table can be reproduced by creating a job which simply does 
'abort(500)' vs a job that does 'abort(404)'

**Comment by marickvantuil** [comment]
Thanks a lot for the bug reports! I have fixed both in `v3.1.4`.
