### ISSUE TITLE
419 response status

### ISSUE THREAD

**Issue by GermanZun** [stackkit/laravel-google-cloud-tasks-queue#59]
Hi. Thanks for your efforts on creating this tool!. I am trying to apply this tool to my laravel project but I don't understand how it works. I created the route for receiving the payload (handle-task) but it gives me a 419 status on calling from a task, because I think it doesn't send a csrf token. When I exclude the route from CSRF verification it works but I can call it from anywhere heh. 

Thanks in advance for the help!

**Comment by marickvantuil** [comment]
Hey, the 'handle-task' route comes out of the box with this package. There is no need to make one manually. Does that clear things up?

**Comment by GermanZun** [comment]
That make a lot of sense now... thanks very much!
