### ISSUE TITLE
Cannot access protected property Illuminate\Queue\Jobs\SyncJob::$job

### ISSUE THREAD

**Issue by Tarpsvo** [stackkit/laravel-google-cloud-tasks-queue#73]
The latest PR and release created the following issue for me:
![image](https://user-images.githubusercontent.com/2018660/196372420-34bb8ad5-ab08-406e-b274-d73a29e556c3.png)

I believe both of the data_set instances in CloudTasksServiceProvider.php cause this issue. How come it's working for the rest of you? The `job` property been protected for a long time.

**Comment by marickvantuil** [comment]
Thanks, I must have missed that. Will check it asap!

**Comment by Kyon147** [comment]
This is happening to me too, dropped back to the previous version at the moment but you probably need to use the accessor method.

**Comment by marickvantuil** [comment]
Can you please check you're not using the `sync` queue?

I am only able to reproduce when setting `QUEUE_CONNECTION` to `sync` (this package kinda breaks other queue drivers when installed, will fix this soon). Also in the screenshot, the `$event->job` is an instance of `Illuminate\Queue\Jobs\SyncJob`, which indeed has a protected property `$job`. When this package is active, `$event->job` should be an instance of `Stackkit\LaravelGoogleCloudTasksQueue\CloudTasksJob` which has a public array `$job` (in which the `data_set` works).

Please let me know!

**Comment by Tarpsvo** [comment]
The automated tests do use the Sync queue driver. I guess the easiest solution here would be to not load the cloud tasks queue service provider when env is set to 'testing'.

However, I think it would be better to check if the $job is a CloudTasksJob and ignore the job if it's something else.

I submitted PR #74 that addresses this. Are there any caveats there? Ie should the dashboard log jobs that are not cloud task jobs?

**Comment by marickvantuil** [comment]
Thanks, I think that looks good! Just merged it and tagged `v3.3.1`.
