### ISSUE TITLE
HttpRequest.url must start with 'https'

### ISSUE THREAD

**Issue by Dejan91** [stackkit/laravel-google-cloud-tasks-queue#77]
Hello. 

I have followed all the instructions provided by the package. I have application running on the google cloud run.
When I try to dispatch job to the queue I get the following error.

Thanks in advance for the help!

exception: "Google\\ApiCore\\ApiException"
file: "/app/vendor/google/gax/src/ApiException.php"
line: 267
message: "{\n    \"message\": \"HttpRequest.url must start with 'https:\\/\\/' for request with HttpRequest.authorization_header\",\n    \"code\": 3,\n    \"status\": \"INVALID_ARGUMENT\",\n    \"details\": []\n}"
trace: [{file: "/app/vendor/google/gax/src/ApiException.php", line: 194, function: "create",…},…]
0: {file: "/app/vendor/google/gax/src/ApiException.php", line: 194, function: "create",…}
1: {file: "/app/vendor/google/gax/src/ApiException.php", line: 315, function: "createFromRestApiResponse",…}
2: {file: "/app/vendor/google/gax/src/Transport/RestTransport.php", line: 145,…}
3: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 204,…}
4: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 153, function: "callHandler",…}5: 
{file: "/app/vendor/guzzlehttp/promises/src/TaskQueue.php", line: 48,…}
6: {file: "/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php", line: 159, function: "run",…}
7: {file: "/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php", line: 184, function: "tick",…}
8: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 248, function: "execute",…}
9: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 224, function: "invokeWaitFn",…}
10: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 269, function: "waitIfPending",…}
11: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 226, function: "invokeWaitList",…}
12: {file: "/app/vendor/guzzlehttp/promises/src/Promise.php", line: 62, function: "waitIfPending",…}
13: {file: "/app/vendor/google/cloud-tasks/src/V2/Gapic/CloudTasksGapicClient.php", line: 529,…}
14: {file: "/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksApiConcrete.php", line: 40,…}
15: {file: "/app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php", line: 338,…}
16: {file: "/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php", line: 172,…}
17: {file: "/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php", line: 99,…}
18: {file: "/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php", line: 82,…}
19: {file: "/app/vendor/laravel/framework/src/Illuminate/Queue/Queue.php", line: 315,…}
20: {file: "/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php", line: 60,…}
21: {file: "/app/vendor/stackkit/laravel-google-cloud-tasks-queue/src/CloudTasksQueue.php", line: 83,…}
22: {file: "/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php", line: 253, function: "push",…}
23: {file: "/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php", line: 229,…}
24: {file: "/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php", line: 77,…}
25: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php", line: 193,…}
26: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php", line: 389,…}
27: {file: "/app/app/Listeners/ExportPortfolioListener.php", line: 15, function: "dispatch"}
28: {file: "/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php", line: 441,…}
29: {file: "/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php", line: 249,…}
30: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php", line: 450,…}
31: {file: "/app/app/Actions/Export/ExportPortfolioAction.php", line: 51, function: "event"}
32: {file: "/app/app/Actions/AbstractAction.php", line: 104, function: "success",…}
33: {file: "/app/app/Http/Controllers/Api/PortfolioController.php", line: 237, function: "run",…}
34: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php", line: 54,…}
35: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php", line: 45,…}
36: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php", line: 261,…}
37: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php", line: 204,…}
38: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 725, function: "run",…}
39: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 141,…}
40: {file: "/app/vendor/tymon/jwt-auth/src/Http/Middleware/Authenticate.php", line: 32,…}
41: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
42: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php",…}
43: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
44: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",…}
45: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",…}
46: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
47: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 116,…}
48: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 726, function: "then",…}
49: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 703,…}
50: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 667,…}
51: {file: "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php", line: 656,…}
52: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line: 189,…}
53: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 141,…}
54: {file: "/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php",…}
55: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
56: {fie: "/app/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php", line: 42,…}
57: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
58: {file: "/app/vendor/laravel/nova/src/Http/Middleware/ServeNova.php", line: 23,…}
59: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
60: {file: "/app/app/Http/Middleware/SetReleaseVersion.php", line: 20,…}
61: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
62: {file: "/app/vendor/fruitcake/laravel-cors/src/HandleCors.php", line: 52,…}
63: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
64: {file: "/app/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php", line: 39,…}
65: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
66: {,…}
67: {,…}
68: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
69: {,…}
70: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php",…}
71: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
72: {,…}
73: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
74: {file: "/app/app/Http/Middleware/CheckForMaintenanceMode.php", line: 45,…}
75: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 180,…}
76: {file: "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php", line: 116,…}
77: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line: 164,…}
78: {file: "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php", line: 133,…}
79: {file: "/app/public/index.php", line: 55, function: "handle",…}

**Comment by marickvantuil** [comment]
Hi, I ran into this before and it happened because the [trusted proxies / trusted hosts](https://laravel.com/docs/9.x/requests#configuring-trusted-proxies) had not been set up correctly. Can you please check that first?

<img width="714" alt="Screenshot 2022-11-05 at 15 21 14" src="https://user-images.githubusercontent.com/647007/200124449-db5814d2-59f9-44d5-901e-16ba504dab2a.png">

**Comment by marickvantuil** [comment]
You can try adding the following to `app/Http/Middleware/TrustProxies.php`:
```php
protected $proxies = '*';
```
Curious to know if that fixed it!
