### ISSUE TITLE
[QUESTION] Is the dashboard viewable?

### ISSUE THREAD

**Issue by LarryBarker** [stackkit/laravel-google-cloud-tasks-queue#92]
Hey there, love the package, thanks for sharing! Question about the dashboard, should it be accessible on a fresh install? Not seeing any routes and getting a 404 when trying to access `/cloud-tasks`. Just want to make sure I'm not missing something?

**Comment by marickvantuil** [comment]
> Hey there, love the package, thanks for sharing!

Thank you!

Did you perform these steps?

> To make use of it, enable it through the .env file:
```
STACKKIT_CLOUD_TASKS_DASHBOARD_ENABLED=true
STACKKIT_CLOUD_TASKS_DASHBOARD_PASSWORD=MySecretLoginPasswordPleaseChangeThis
```
> Then publish its assets and migrations:
```
php artisan vendor:publish --tag=cloud-tasks
php artisan migrate
```
> The dashboard is accessible at the URI: /cloud-tasks


It has to be enabled manually because it requires a database and has a small performance hit (as it has to track each job status change), not something I think is necessary or useful for every application
